apiVersion: v2
name: opencode-server
description: Hardened OpenCode server for Kubernetes
type: application
version: "1.2.0"
appVersion: "1.18.19"
keywords:
  - ai
  - coding-agent
  - opencode
  - llm
  - development
home: https://github.com/aardbol/opencode-server
sources:
  - https://github.com/aardbol/opencode-server
maintainers:
  - name: Leonardo (aardbol)
    url: https://github.com/aardbol
annotations:
  artifacthub.io/maintainers: |
    - name: aardbol
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: source
      url: https://github.com/aardbol/opencode-server
    - name: support
      url: https://github.com/aardbol/opencode-server/issues
  artifacthub.io/changes: |
    - kind: added
      description: Support for opencode v1.18.19
    - kind: fixed
      description: Removed OPENCODE_CONFIG because its implementation in opencode is buggy
    - kind: fixed
      description: Probes needed authentication to access /global/health
