{{- if not .Values.auth.existingSecret }}
{{- if or .Values.auth.basic.enabled .Values.auth.apiKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencode.secretName" . }}
  labels:
    {{- include "opencode.labels" . | nindent 4 }}
  {{- with .Values.auth.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.auth.basic.enabled }}
  {{- if .Values.auth.basic.password }}
  {{ .Values.auth.basic.passwordKey }}: {{ .Values.auth.basic.password | quote }}
  {{- end }}
  {{- end }}
  {{- range $key, $val := .Values.auth.apiKeySecret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
