name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: upcloud-tools/gha-actions/.github/workflows/dependency-review.yaml@c0df829cbad57268497db8cfb6174419f925b283
