name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  scorecard:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: upcloud-tools/gha-actions/.github/workflows/scorecard.yaml@7aa82abc666a4b8107e5c5f1a6c42b49f5f42268
