name: Trivy Scan

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_run:
    workflows: [Container Build]
    types: [completed]

permissions:
  contents: read

jobs:
  trivy:
    permissions:
      contents: read
      actions: read
      packages: read
      security-events: write
    uses: upcloud-tools/gha-actions/.github/workflows/trivy.yaml@7aa82abc666a4b8107e5c5f1a6c42b49f5f42268
    with:
      image_repo: ghcr.io/${{ github.repository }}
